<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0</TargetFrameworks>
		<NuspecFile>$(MSBuildThisFileDirectory)NUnitRetry.ReqnrollPlugin.nuspec</NuspecFile>
		<NuspecProperties>version=$(PackageVersion)</NuspecProperties>
		<AssemblyName>NUnitRetry.ReqnrollPlugin</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Reqnroll.CustomPlugin" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\NUnitRetry\NUnitRetry.csproj" />
	</ItemGroup>
	
</Project>
